version: '3'
services:
  database:
    container_name: postgres-csc2020
    image: postgres:latest
    ports:
    - "5433:5432"
    volumes:
    - \Users\fatim\Desktop\CSC202-2020set
    env_file:
    - csc2020.env